name: Deploy

on:
  workflow_run:
    workflows: ['Build And Test']
    types: [completed]
    branches:
      - 'main'

jobs:
  merge-and-deploy:
    name: Merge main to production and deploy
    runs-on: ubuntu-latest

    # Chỉ chạy nếu workflow "Build And Test" thành công
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      # Checkout repository để merge
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Thiết lập Git credentials
      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # Merge main vào production
      - name: Merge main into production
        run: |
          git checkout production
          git merge main --no-ff --no-edit
          git push origin production
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Cài đặt SSH keys
      - name: Install SSH keys
        run: |
          echo "Debug: SSH_HOST is ${{ secrets.SSH_HOST }}"
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_HOST }} || { echo "ssh-keyscan failed"; exit 1; }
          ssh-keyscan -H -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      # Kết nối và pull nhánh production
      - name: Connect and pull production
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && git checkout production && git pull && exit"

      # Chạy composer install (không xóa composer.lock)
      - name: Composer install
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && composer install --no-ansi --no-interaction --no-progress && exit"

      # Chạy migration
      - name: Run php artisan migrate
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && php artisan migrate --force && exit"

      # Khởi động lại PHP-FPM
      - name: Restart PHP-FPM and set permissions
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "service php8.2-fpm restart && chmod -R 777 /var/run/php"

      # Dọn dẹp SSH
      - name: Cleanup
        run: rm -rf ~/.ssh
